# Generated by Django 6.1.1 on 2026-09-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('KG', 'Quilo'), ('L', 'Litro'), ('UN', 'Unidade')], max_length=2)),
                ('data_validade', models.DateField()),
                ('consumo_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('houve_ruptura', models.BooleanField(default=False)),
            ],
        ),
    ]
